export const menuItems = [
  {
    id: 'services',
    icon: 'Home',
    label: 'Mes services',
    href: '#card-0',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'about',
    icon: 'User',
    label: 'À propos',
    href: '#card-1',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'portfolio',
    icon: 'GalleryHorizontal',
    label: 'Portfolio',
    href: '#card-2',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'experience',
    icon: 'BriefcaseBusiness',
    label: 'Expériences',
    href: '#card-3',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'resume',
    icon: 'ClipboardList',
    label: 'CV',
    href: '/documents/resume.pdf',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'motivation',
    icon: 'PenTool',
    label: 'Lettre de motivation',
    href: '/documents/motivation.pdf',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'linkedin',
    icon: 'Linkedin',
    label: 'LinkedIn',
    href: 'www.linkedin.com/in/fabien-thiesset',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'github',
    icon: 'Github',
    label: 'GitHub',
    href: 'https://github.com/ThiessetFabien?tab=repositories',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'contact',
    icon: 'Mail',
    label: 'Envoyez-moi un message',
    href: 'mailto:thiessetfabienpro@gmail.com',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'phone',
    icon: 'Phone',
    label: 'Appelez-moi directement',
    href: 'tel:+33610920974',
  },
];
