export const menuItems = [
  {
    id: 'services',
    icon: 'Home',
    label: 'Découvrez mes services',
    href: '/',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'about',
    icon: 'User',
    label: 'Apprenez à me connaître',
    href: '#about',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'portfolio',
    icon: 'GalleryHorizontal',
    label: 'Explorez mes projets',
    href: '#portfolio',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'experience',
    icon: 'BriefcaseBusiness',
    label: 'Découvrez mon parcours',
    href: '#experience',
    target: '_self',
    rel: 'noopener noreferrer',
  },
  {
    id: 'resume',
    icon: 'ClipboardList',
    label: 'Téléchargez mon CV',
    href: '/documents/resume.pdf',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'motivation',
    icon: 'PenTool',
    label: 'Lisez ma motivation',
    href: '/documents/motivation.pdf',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'linkedin',
    icon: 'Linkedin',
    label: 'Rejoignez-moi sur LinkedIn',
    href: 'www.linkedin.com/in/fabien-thiesset',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'github',
    icon: 'Github',
    label: 'Découvrez mon GitHub',
    href: 'https://github.com/ThiessetFabien?tab=repositories',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'contact',
    icon: 'Mail',
    label: 'Envoyez-moi un message',
    href: 'mailto:thiessetfabienpro@gmail.com',
    target: '_blank',
    rel: 'noopener noreferrer',
  },
  {
    id: 'phone',
    icon: 'Phone',
    label: 'Appelez-moi directement',
    href: 'tel:+33610920974',
  },
];
